---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: nebotask
  region: us-east-1
  version: "1.26"
availabilityZones:
- us-east-1a
- us-east-1b
managedNodeGroups:
- name: managed-nodes
  labels:
    role: managed-nodes
  instanceType: t3.small
  minSize: 1
  maxSize: 5
  desiredCapacity: 1
  volumeSize: 20
